package ru.tanexc.meal.domain.model

import com.fasterxml.jackson.annotation.JsonProperty
import ru.tanexc.meal.data.local.entity.MealEntity
import ru.tanexc.meal.domain.Domain

data class Meal(
    @JsonProperty("idMeal") val id: Long,
    @JsonProperty("strMeal") val title: String?,
    @JsonProperty("strDrinkAlternate") val drinkAlternate: String?,
    @JsonProperty("strCategory") val category: String?,
    @JsonProperty("strArea") val area: String?,
    @JsonProperty("strInstructions") val instructions: String?,
    @JsonProperty("strMealThumb") val thumb: String?,
    @JsonProperty("strTags") val tags: String?,
    @JsonProperty("strYoutube") val youtubeLink: String?,

    @JsonProperty("strIngredient1") val ingredient1: String?,
    @JsonProperty("strIngredient2") val ingredient2: String?,
    @JsonProperty("strIngredient3") val ingredient3: String?,
    @JsonProperty("strIngredient4") val ingredient4: String?,
    @JsonProperty("strIngredient5") val ingredient5: String?,
    @JsonProperty("strIngredient6") val ingredient6: String?,
    @JsonProperty("strIngredient7") val ingredient7: String?,
    @JsonProperty("strIngredient8") val ingredient8: String?,
    @JsonProperty("strIngredient9") val ingredient9: String?,
    @JsonProperty("strIngredient10") val ingredient10: String?,
    @JsonProperty("strIngredient11") val ingredient11: String?,
    @JsonProperty("strIngredient12") val ingredient12: String?,
    @JsonProperty("strIngredient13") val ingredient13: String?,
    @JsonProperty("strIngredient14") val ingredient14: String?,
    @JsonProperty("strIngredient15") val ingredient15: String?,
    @JsonProperty("strIngredient16") val ingredient16: String?,
    @JsonProperty("strIngredient17") val ingredient17: String?,
    @JsonProperty("strIngredient18") val ingredient18: String?,
    @JsonProperty("strIngredient19") val ingredient19: String?,
    @JsonProperty("strIngredient20") val ingredient20: String?,

    @JsonProperty("strMeasure1") val measure1: String?,
    @JsonProperty("strMeasure2") val measure2: String?,
    @JsonProperty("strMeasure3") val measure3: String?,
    @JsonProperty("strMeasure4") val measure4: String?,
    @JsonProperty("strMeasure5") val measure5: String?,
    @JsonProperty("strMeasure6") val measure6: String?,
    @JsonProperty("strMeasure7") val measure7: String?,
    @JsonProperty("strMeasure8") val measure8: String?,
    @JsonProperty("strMeasure9") val measure9: String?,
    @JsonProperty("strMeasure10") val measure10: String?,
    @JsonProperty("strMeasure11") val measure11: String?,
    @JsonProperty("strMeasure12") val measure12: String?,
    @JsonProperty("strMeasure13") val measure13: String?,
    @JsonProperty("strMeasure14") val measure14: String?,
    @JsonProperty("strMeasure15") val measure15: String?,
    @JsonProperty("strMeasure16") val measure16: String?,
    @JsonProperty("strMeasure17") val measure17: String?,
    @JsonProperty("strMeasure18") val measure18: String?,
    @JsonProperty("strMeasure19") val measure19: String?,
    @JsonProperty("strMeasure20") val measure20: String?,

    @JsonProperty("strSource") val sourceLink: String?,
    @JsonProperty("strImageSource") val imageSource: String?,
    @JsonProperty("strCreativeCommonsConfirmed") val creativeCommonsConfirmed: String?,
    @JsonProperty("dateModified") val dateModified: Long?
) : Domain {
    override fun asData(): MealEntity = MealEntity(
        id,
        title ?: "",
        drinkAlternate ?: "",
        category ?: "",
        area ?: "",
        instructions ?: "",
        thumb ?: "",
        tags ?: "",
        youtubeLink ?: "",
        ingredient1 ?: "",
        ingredient2 ?: "",
        ingredient3 ?: "",
        ingredient4 ?: "",
        ingredient5 ?: "",
        ingredient6 ?: "",
        ingredient7 ?: "",
        ingredient8 ?: "",
        ingredient9 ?: "",
        ingredient10 ?: "",
        ingredient11 ?: "",
        ingredient12 ?: "",
        ingredient13 ?: "",
        ingredient14 ?: "",
        ingredient15 ?: "",
        ingredient16 ?: "",
        ingredient17 ?: "",
        ingredient18 ?: "",
        ingredient19 ?: "",
        ingredient20 ?: "",
        measure1 ?: "",
        measure2 ?: "",
        measure3 ?: "",
        measure4 ?: "",
        measure5 ?: "",
        measure6 ?: "",
        measure7 ?: "",
        measure8 ?: "",
        measure9 ?: "",
        measure10 ?: "",
        measure11 ?: "",
        measure12 ?: "",
        measure13 ?: "",
        measure14 ?: "",
        measure15 ?: "",
        measure16 ?: "",
        measure17 ?: "",
        measure18 ?: "",
        measure19 ?: "",
        measure20 ?: "",
        sourceLink ?: "",
        imageSource ?: "",
        creativeCommonsConfirmed ?: "",
        dateModified
    )
}